Updates to docker file

diff --git a/bin/boot b/bin/boot
--- a/bin/boot
+++ b/bin/boot
@@ -1,31 +1,7 @@
 #!/bin/bash
-# Copyright 2014 Joukou Ltd
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#   http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
 
-#
-# This script starts Basho Riak 2.x in a Docker container after some basic
-# initial configuration.
-#
-# Riak will listen on the eth0 interface which is the interface through which a
-# container speaks to the bridge.
-#
-# To set the Erlang cookie for Riak clustering override RIAK_COOKIE
+set -o pipefail
 
-# fail hard and fast even on pipelines
-set -eo pipefail
-
-# set debug based on envvar
 [[ $DEBUG ]] && set -x
 
 function main {
@@ -36,14 +12,23 @@ function main {
   export RIAK_HTTP_ADDR="${RIAK_IPV4}:8098"
   export RIAK_PROTOBUF_ADDR="${RIAK_IPV4}:8087"
   export RIAK_NODENAME="riak@${RIAK_IPV4}"
+  RUNNER_BASE_DIR=/usr/lib/riak
+  RUNNER_LOG_DIR=/var/log/riak
+  PIPE_DIR=/tmp/riak/
+  START_ERL=`cat $RUNNER_BASE_DIR/releases/start_erl.data`
+  ERTS_VSN=${START_ERL% *}
+  ERTS_PATH=$RUNNER_BASE_DIR/erts-$ERTS_VSN/bin
+
+  # make sure directories exist
+  mkdir -p $RUNNER_LOG_DIR
+  mkdir -p $PIPE_DIR
 
   # set riak data and log directory permissions
-  chown -R riak:riak /var/lib/riak /var/log/riak
+  chown -R riak:riak /var/lib/riak /var/log/riak /tmp/riak
   chmod 755 /var/lib/riak /var/log/riak
 
   # Open file descriptor limit
   ulimit -n 100000
-
 
   # update riak.conf
   cat /etc/riak/riak.conf.tmpl | envsubst "$(cat /etc/riak/riak.conf.envsubst | tr '\n' ' ')" \
@@ -53,23 +38,42 @@ function main {
   riak chkconfig
 
   # start riak
-  #exec /sbin/setuser riak "$(ls -d /usr/lib/riak/erts*)/bin/run_erl" "/tmp/riak" \
-  # "/var/log/riak" "exec /usr/sbin/riak console"
+  #exec /sbin/setuser riak "$(ls -d /usr/lib/riak/erts*)/bin/run_erl" "/tmp/riak" "/var/log/riak" "exec /usr/sbin/riak console"
   riak start
 
   echo "riak started"
 
-  sleep 10
+  sleep 5;
   # Join node to the cluster
-  if /usr/local/bin/etcdctl ls /riak/machines 3>&1 1>&2 2>&3 | grep -v $RIAK_IPV4 | grep -v Error;
-    then
-    IP=$(/usr/local/bin/etcdctl ls /riak/machines | grep -v $RIAK_IPV4 | cut -f4 -d"/" | sort -R | head -n 1)
-    riak-admin cluster join "riak@$IP" > /dev/null 2>&1;
-    sleep 5;
-    riak-admin cluster plan > /dev/null 2>&1 && riak-admin cluster commit > /dev/null 2>&1;
+  echo "clustering riak"
+
+  /usr/local/bin/etcdctl ls /riak/machines | grep -v $RIAK_IPV4
+  found=$?
+  if [[ $found -eq 0 ]] ; then
+    echo "Checking if already joined cluster"
+    riak-admin member-status | grep -q "Valid:1 "
+    clustered=$?
+    if [[ $clustered -eq 0 ]] ; then
+      IP=$(/usr/local/bin/etcdctl ls /riak/machines | grep -v $RIAK_IPV4 | cut -f4 -d"/" | sort -R | head -n 1)
+      echo "clustering riak using seed $IP"
+      riak-admin cluster join "riak@$IP";
+      sleep 5;
+      riak-admin cluster plan && riak-admin cluster commit;
+      echo "clustered riak yo"
+    else
+      echo "This node is already a member of the cluster"
+
+    fi
+  else
+    echo "Cannot find seek machine. First machine or didn't join cluster."
   fi
 
-  tail -f /var/log/riak/erlang.log.*
+  echo "attaching to console"
+
+  set -e
+
+  exec /sbin/setuser riak $ERTS_PATH/run_erl $PIPE_DIR $RUNNER_LOG_DIR "exec /usr/sbin/riak attach"
+
 }
 
 main
